### ISSUE TITLE
How to set the database of MMS?

### ISSUE THREAD

**Issue by zhang-chi-IGGCAS** [louis-richard/irfu-python#1]
Dear Louis Richard,

          I do not know how to set the path of MMS database of pyrfu. 
       for example, in irf-matlab-master, we have to type: 
                            mms.db_init (' local_file_db ', path of database);
        But I do not know how to do it in this python code

thanks a lot!

**Comment by louis-richard** [comment]
Dear Zhang Chi,
Indeed the way to setup the database path is different from that used in irfu-matlab. In the current version of pyrfu, you need to pass and extra argument to the mms.get_data() routine (see https://pyrfu.readthedocs.io/en/latest/_generated/pyrfu.mms.get_data.html).
Hope this will help.

**Comment by zhang-chi-IGGCAS** [comment]
Dear Richard, 

        yes, using this code could solve this problem

        b_xyz = mms.get_data("B_gse_fgm_brst_l2", tint_brst, 1,  data_path='F:/MMS/mms_db/data/')

thanks a lot

**Comment by zhang-chi-IGGCAS** [comment]
Dear Richard,
        there are stil some problems in here. 
       should we revise the data path in config.py?

CONFIG = {"local_data_dir": "F:/MMS/mms_db/data/",
          'mirror_data_dir': None,  # e.g., '/Volumes/data_network/data/mms'
          'debug_mode': False,
          'download_only': False,
          'no_download': False}


or in the get_data.py?
       
def get_data(var_str, tint, mms_id, verbose: bool = True,
             data_path='F:/MMS/mms_db/data/'):

I have tried both of them, but still no files can be found.

**Comment by louis-richard** [comment]
Dear Zhang Chi,
I uploaded the version 2.3.9 to the python index. This new version contains a routine, named mms.db_init, that setup the path in the configuration file (config.json). Hence, you don't need to give the data_path to the mms.get_data anymore.

Besides, if I'm correct you are using a Windows machine, so I think that the problem you are facing may be due to the different path convention on Windows. You should check the path using os.path.normpath('F:/MMS/mms_db/data/') == 'F:/MMS/mms_db/data/'. Note that the new mms.db_init uses os.path.normpath, so in principle you will not face such problem anymore.

Hope this will work fine.

**Comment by zhang-chi-IGGCAS** [comment]
Dear Richard,
    it works well now, thanks a lot!
   This code will significantly help us to analyze the data!

best regards
